// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 GameKit contributors
// REUSE-IgnoreStart

using System;
using Microsoft.CodeAnalysis;

namespace GameKit.Build;

/// <summary>
/// Roslyn incremental source generator that emits a per-assembly
/// <c>internal static partial class GameKitMarker</c> carrying the
/// MinVer-resolved <c>$(Version)</c> and the consuming
/// <c>$(AssemblyName)</c> as compile-time constants.
/// </summary>
/// <remarks>
/// <para>
/// Consumed at runtime by <c>GameKitVersionAssertionHostedService</c>
/// (Plan 06-02) to fail fast on cross-assembly version mismatch in the
/// coordinated release train (D-15, OPS-04, OPS-05).
/// </para>
/// <para>
/// Wired into every shipped <c>src/GameKit.*/*.csproj</c> via
/// <c>OutputItemType=&quot;Analyzer&quot; ReferenceOutputAssembly=&quot;false&quot;</c>.
/// The generator runs at compile time; its DLL never ships.
/// </para>
/// </remarks>
[Generator]
public sealed class GameKitVersionGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Read MinVer-resolved $(Version). The CompilerVisibleProperty
        // declaration in Directory.Build.props makes this readable here.
        // Fallback "0.0.0" surfaces a wiring bug at the OPS-04 test (the
        // smoke run in Plan 06-01 Task 4 explicitly asserts the value
        // is NOT this literal).
        var version = context.AnalyzerConfigOptionsProvider.Select((p, _) =>
            p.GlobalOptions.TryGetValue("build_property.Version", out var v) ? v : "0.0.0");

        // Read $(AssemblyName) — gates emission on the GameKit.* prefix
        // so the generator never accidentally injects the marker into a
        // non-GameKit consumer's compilation (defense-in-depth: the
        // generator is only ProjectRef'd from GameKit src/* csprojs).
        var asmName = context.CompilationProvider.Select((c, _) => c.AssemblyName ?? "Unknown");

        var combined = version.Combine(asmName);
        context.RegisterSourceOutput(combined, (spc, tuple) =>
        {
            var (ver, name) = tuple;

            // Case-sensitive Ordinal compare per 06-RESEARCH Pattern 5
            // line 644 — never accept "gamekit." / "Gamekit." etc.
            if (!name.StartsWith("GameKit.", StringComparison.Ordinal))
            {
                return;
            }

            var ns = name + ".Internal";
            var src =
                "// <auto-generated/>\n" +
                "// Emitted by GameKit.Build source generator.\n" +
                "// SPDX-License-Identifier: Apache-2.0\n" +
                "namespace " + ns + ";\n" +
                "\n" +
                "internal static partial class GameKitMarker\n" +
                "{\n" +
                "    public const string GameKitVersion = \"" + ver + "\";\n" +
                "    public const string AssemblyName   = \"" + name + "\";\n" +
                "}\n";

            spc.AddSource("GameKitMarker.g.cs", src);
        });
    }
}
// REUSE-IgnoreEnd
