// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 GameKit contributors

using System;

namespace GameKit.Lobby.Entities;

/// <summary>
/// Join-row binding a <see cref="Lobby"/> to a <c>Player</c>. References the canonical
/// <c>gamekit.players.Id</c> — Steam-linked and Discord-linked players can share a lobby
/// because both identities share a single <c>Player</c> row (CONTEXT.md D-05; Phase 2's
/// multi-identity model).
/// </summary>
/// <remarks>
/// <para>
/// The composite unique constraint on <c>(LobbyId, PlayerId)</c> prevents duplicate-member
/// rows for the same lobby + player pair (LOBBY-02; T-11-02-03).
/// </para>
/// <para>
/// Both FKs use <c>ON DELETE CASCADE</c>: lobby deletion cascades to membership rows (GDPR
/// convenience), and player hard-deletion cascades to membership rows (GDPR tombstoning).
/// This deviates from <c>PartyMember</c> which uses <c>Restrict</c> on the player FK — lobby
/// membership has no audit purpose, making cascade the correct choice here.
/// </para>
/// </remarks>
public sealed class LobbyMember
{
    /// <summary>Row id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>FK → <see cref="Lobby.Id"/> (ON DELETE CASCADE — dropping a lobby drops its members).</summary>
    public Guid LobbyId { get; set; }

    /// <summary>
    /// FK → <c>gamekit.players.Id</c> (the canonical player, NOT a <c>player_identity</c>).
    /// ON DELETE CASCADE — GDPR player deletion cascades to lobby membership.
    /// </summary>
    public Guid PlayerId { get; set; }

    /// <summary>
    /// Whether this member has indicated readiness during a
    /// <see cref="LobbyState.ReadyChecking"/> phase.
    /// </summary>
    public bool Ready { get; set; }

    /// <summary>UTC timestamp at which the player joined the lobby.</summary>
    public DateTimeOffset JoinedAt { get; set; }
}
