// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 GameKit contributors

using System;
using System.Collections.Generic;

namespace GameKit.Lobby.Entities;

/// <summary>
/// A durable lobby row — persistent group backed by Postgres (LOBBY-02). Has an owner
/// <see cref="OwnerId"/>, an optional ladder reference <see cref="LadderId"/>, a lifecycle
/// state machine (<see cref="LobbyState"/>), a configurable <see cref="MaxMembers"/> cap,
/// an optional <see cref="RegionName"/> for pool-affinity during matchmaking, and creation /
/// modification timestamps.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="State"/> is stored as <c>integer</c> at the SQL level (Phase 5 mandatory pattern —
/// <c>HasConversion&lt;string&gt;()</c> is forbidden; see CLAUDE.md).
/// </para>
/// <para>
/// <see cref="OwnerId"/> uses <c>ON DELETE SET NULL</c> so a lobby persists when the owner
/// disconnects or is deleted — ownership transfer is handled in application code. <see cref="LadderId"/>
/// also uses <c>ON DELETE SET NULL</c> so lobby rows survive ladder deletion.
/// </para>
/// </remarks>
public sealed class Lobby
{
    /// <summary>Lobby id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// FK → <c>gamekit.players.Id</c> of the lobby owner. Nullable — set to <c>null</c> if
    /// the owning player is deleted (<c>ON DELETE SET NULL</c>).
    /// </summary>
    public Guid? OwnerId { get; set; }

    /// <summary>
    /// FK → <c>gamekit.ladders.Id</c>. Nullable — lobbies may exist without a ladder (casual
    /// play). Set to <c>null</c> if the ladder is deleted (<c>ON DELETE SET NULL</c>).
    /// </summary>
    public Guid? LadderId { get; set; }

    /// <summary>
    /// Lifecycle state. Stored as <c>integer</c> (Phase 5 mandatory) — no
    /// <c>HasConversion&lt;string&gt;()</c> applied.
    /// </summary>
    public LobbyState State { get; set; }

    /// <summary>
    /// Maximum number of members this lobby accepts before transitioning to
    /// <see cref="LobbyState.Closed"/>. Defaults to 8.
    /// </summary>
    public int MaxMembers { get; set; } = 8;

    /// <summary>
    /// Optional pool-affinity name passed to matchmaking when the lobby submits a ticket.
    /// Maps to the <c>PoolName</c> / <c>RegionName</c> field on <c>MatchmakingTicket</c>.
    /// </summary>
    public string? RegionName { get; set; }

    /// <summary>UTC timestamp at which the lobby row was created.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>UTC timestamp of the most recent state or membership change.</summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>Navigation to member rows. Populated when explicitly loaded.</summary>
    public ICollection<LobbyMember> Members { get; set; } = new List<LobbyMember>();
}
