// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 GameKit contributors

using System;
using System.Collections.Generic;

namespace GameKit.Matchmaking.Strategy;

/// <summary>
/// The pure output of <see cref="IMatchmakingStrategy.Match"/> on a successful match.
/// The matchmaker ticker (Plan 05-05) consumes this record to drive the atomic Lua
/// claim (Plan 05-04 Task 3) + proposal write (Plan 05-06).
/// </summary>
/// <remarks>
/// <para>
/// <see cref="ProposalId"/> is generated by the strategy (UUIDv4 / random Guid) and is
/// the canonical identifier carried through the atomic Lua claim into the Redis proposal
/// hash <c>mm:proposal:{id}</c>. The ticker passes this same id when invoking
/// <c>AtomicClaimScript.ExecuteAsync</c> (Task 3).
/// </para>
/// <para>
/// <see cref="MatchedTickets"/> includes the original candidate plus every ticket the
/// strategy selected from the pool. The first element is the candidate by convention; the
/// rest are pool entries in queue-age order (oldest-waiter-first, per Pitfall §6).
/// </para>
/// <para>
/// <see cref="TeamAssignments"/> maps player id → team index (0 / 1 in v1's 2-team mode).
/// v1 ships random team assignment driven by a <see cref="System.Security.Cryptography.RandomNumberGenerator"/>;
/// MMR-balanced split is deferred to a future phase (CONTEXT §Phase Boundary).
/// </para>
/// </remarks>
/// <param name="ProposalId">Strategy-minted proposal id propagated through the Lua claim into <c>mm:proposal:{id}</c>.</param>
/// <param name="MatchedTickets">Candidate + selected pool entries (candidate at index 0; others in oldest-waiter-first order).</param>
/// <param name="TeamAssignments">Player → team index map (v1: random 0/1 split).</param>
public sealed record MatchResult(
    Guid ProposalId,
    IReadOnlyList<QueuedParty> MatchedTickets,
    IReadOnlyDictionary<Guid, int> TeamAssignments);
