// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 GameKit contributors

using System;
using System.Text.Json;

namespace GameKit.Rankings.Entities;

/// <summary>
/// A named competitive ladder. Every <c>GameSession</c> references at most one ladder;
/// the ranking algorithm applies batch updates within each ladder independently (D-01/D-02).
/// </summary>
/// <remarks>
/// <para>
/// Ladders are registered at build time via <c>services.AddLadder("name", config)</c> (D-21)
/// and upserted into this table at startup by <c>StartupLadderUpserter</c>.
/// Runtime CRUD is deferred to v2.
/// </para>
/// <para>
/// <c>Config</c> is a sparse JSONB column for per-ladder overrides (rating period, regression
/// factor, etc.). Per CORE-17 constraints: infrequently-written, non-relational data only.
/// </para>
/// </remarks>
public sealed class Ladder
{
    /// <summary>Ladder id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Operator-supplied ladder name. Case-insensitive uniqueness enforced via
    /// <c>citext</c> column type (mirrors <c>PlayerCredential.Username</c>).
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Identifier of the ranking algorithm to use for this ladder (e.g. <c>"glicko2"</c>).
    /// Resolved to an <c>IRankingAlgorithm</c> implementation at tick time.
    /// </summary>
    public required string Algorithm { get; set; }

    /// <summary>Whether this ladder accepts new sessions and is included in ticker scans.</summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Sparse per-ladder configuration (JSONB). Overridable fields: <c>DefaultRating</c>,
    /// <c>DefaultRd</c>, <c>DefaultVolatility</c>, <c>RatingPeriod</c>, <c>SeasonResetPolicy</c>
    /// and per-variant fields. Per CORE-17: non-relational, infrequently-written only.
    /// </summary>
    public JsonDocument? Config { get; set; }

    /// <summary>UTC timestamp at which this ladder row was created.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp at which the ticker last drained pending rating updates for this ladder.
    /// Null until the first drain. The ticker uses this to determine whether the configured
    /// <c>RatingPeriod</c> has elapsed since the last batch.
    /// </summary>
    public DateTimeOffset? LastDrainedAt { get; set; }
}
