// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 GameKit contributors

using System;
using System.Text.Json;

namespace GameKit.Core.Entities;

/// <summary>
/// A single game session — the unit of gameplay GameKit tracks for rating updates,
/// participation snapshots, and admin auditing.
/// </summary>
public sealed class GameSession
{
    /// <summary>Session id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>Current lifecycle state. Use <see cref="Start"/> / <see cref="Complete"/> / <see cref="Cancel"/> / <see cref="Abandon"/> to transition; direct assignment is permitted for EF materialization only.</summary>
    public GameSessionState State { get; set; } = GameSessionState.Pending;

    /// <summary>Optional ladder id this session belongs to. Null for unranked or casual sessions. FK constraint lands in Phase 4 when the ladders table arrives.</summary>
    public Guid? LadderId { get; set; }

    /// <summary>UTC timestamp at which the session row was created.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>UTC timestamp at which the session transitioned from Pending to Active. Null until started.</summary>
    public DateTimeOffset? StartedAt { get; set; }

    /// <summary>UTC timestamp at which the session reached a terminal state (Completed / Cancelled / Abandoned). Null while non-terminal.</summary>
    public DateTimeOffset? CompletedAt { get; set; }

    /// <summary>Sparse JSONB metadata per CORE-17 constraints. Do not query on it.</summary>
    public JsonDocument? Metadata { get; set; }

    /// <summary>
    /// Idempotency key set at match-formation time to the proposal id (SCALE-03).
    /// A partial unique index on this column prevents duplicate <c>game_sessions</c> rows
    /// when split-brain replicas both attempt to create the same session.
    /// Null for sessions created outside the matchmaking path (manual API calls).
    /// </summary>
    public string? IdempotencyKey { get; set; }

    /// <summary>Transition from <see cref="GameSessionState.Pending"/> to <see cref="GameSessionState.Active"/>.</summary>
    /// <param name="now">Authoritative UTC clock reading (typically from <c>IClock</c>).</param>
    /// <exception cref="InvalidGameSessionTransitionException">Thrown when the current state is not <see cref="GameSessionState.Pending"/>.</exception>
    public void Start(DateTimeOffset now)
    {
        if (!GameSessionStateTransitions.IsValidTransition(State, GameSessionState.Active))
            throw new InvalidGameSessionTransitionException(State, GameSessionState.Active);
        State = GameSessionState.Active;
        StartedAt = now;
    }

    /// <summary>Transition to <see cref="GameSessionState.Completed"/>. Only permitted from <see cref="GameSessionState.Active"/>.</summary>
    /// <param name="now">Authoritative UTC clock reading.</param>
    /// <exception cref="InvalidGameSessionTransitionException">Thrown when the current state does not permit this transition.</exception>
    public void Complete(DateTimeOffset now)
    {
        if (!GameSessionStateTransitions.IsValidTransition(State, GameSessionState.Completed))
            throw new InvalidGameSessionTransitionException(State, GameSessionState.Completed);
        State = GameSessionState.Completed;
        CompletedAt = now;
    }

    /// <summary>Transition to <see cref="GameSessionState.Cancelled"/>. Permitted from <see cref="GameSessionState.Pending"/> or <see cref="GameSessionState.Active"/>.</summary>
    /// <param name="now">Authoritative UTC clock reading.</param>
    /// <exception cref="InvalidGameSessionTransitionException">Thrown when the current state does not permit this transition.</exception>
    public void Cancel(DateTimeOffset now)
    {
        if (!GameSessionStateTransitions.IsValidTransition(State, GameSessionState.Cancelled))
            throw new InvalidGameSessionTransitionException(State, GameSessionState.Cancelled);
        State = GameSessionState.Cancelled;
        CompletedAt = now;
    }

    /// <summary>Transition to <see cref="GameSessionState.Abandoned"/>. Only permitted from <see cref="GameSessionState.Active"/>.</summary>
    /// <param name="now">Authoritative UTC clock reading.</param>
    /// <exception cref="InvalidGameSessionTransitionException">Thrown when the current state does not permit this transition.</exception>
    public void Abandon(DateTimeOffset now)
    {
        if (!GameSessionStateTransitions.IsValidTransition(State, GameSessionState.Abandoned))
            throw new InvalidGameSessionTransitionException(State, GameSessionState.Abandoned);
        State = GameSessionState.Abandoned;
        CompletedAt = now;
    }
}
