// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 GameKit contributors

using System;
using System.Text.Json;

namespace GameKit.Core.Entities;

/// <summary>
/// A GameKit player — the top-level identity all game sessions, ratings, and audit events refer to.
/// </summary>
/// <remarks>
/// Per GDPR design decision D-13, players are hard-deleted on erasure request; there is no
/// <c>deleted_at</c> soft-delete column. Historical references (session_participants, rating_history,
/// matchmaking_tickets) use <c>ON DELETE SET NULL</c> so opponent data survives erasure while
/// the deleted player's PII leaves the database entirely.
/// </remarks>
public sealed class Player
{
    /// <summary>Player id — UUIDv7 (time-ordered) generated by the registered <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>Public display name. Uniqueness is not enforced at the schema level (v1 decision).</summary>
    public required string DisplayName { get; set; }

    /// <summary>UTC timestamp at which the player row was created.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>UTC timestamp of the player's most recent authenticated or heartbeat activity. Nullable until the first seen event.</summary>
    public DateTimeOffset? LastSeenAt { get; set; }

    /// <summary>True iff the player is currently banned. When true, authentication paths reject.</summary>
    public bool IsBanned { get; set; }

    /// <summary>UTC timestamp at which the ban was applied. Null when <see cref="IsBanned"/> is false.</summary>
    public DateTimeOffset? BannedAt { get; set; }

    /// <summary>Free-text reason for the ban (max 500 chars). Null when not banned.</summary>
    public string? BanReason { get; set; }

    /// <summary>
    /// Sparse, non-relational metadata (JSONB). Per CORE-17, this column is for infrequently-written,
    /// non-queryable game-specific annotations (e.g. preferred locale, client hint). Do not query on it.
    /// Do not treat it as a scratch pad for relational data that deserves its own table.
    /// </summary>
    public JsonDocument? Metadata { get; set; }
}
