// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 GameKit contributors

using System;

namespace GameKit.Matchmaking.Entities;

/// <summary>
/// Per-player cooldown-tracking row appended when a player declines or times out a match
/// proposal (CONTEXT.md D-08). Survives app restart; cooldown lockout is enforced at the
/// <c>POST /api/mm/queue</c> endpoint by querying the rolling window of recent rows.
/// </summary>
/// <remarks>
/// <para>
/// Escalating cooldown ladder: 3 min → 15 min → 30 min within a configurable window
/// (defaults live in <c>GameKitMatchmakingOptions</c>). The lockout check uses the index
/// on <c>(PlayerId, DeclinedAt DESC)</c> for efficient rolling-window queries.
/// </para>
/// <para>
/// <see cref="ProposalId"/> is stored as <c>text</c> at the SQL level rather than a FK
/// to a proposal table — proposals live in Redis with a TTL (RESEARCH §Decision 8 +
/// CONTEXT.md "Claude's Discretion"). Storing the id durably here lets analytics correlate
/// declines back to a specific proposal even after the Redis hash expires.
/// </para>
/// </remarks>
public sealed class DeclineHistory
{
    /// <summary>Row id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>FK → <c>gamekit.players.Id</c>. ON DELETE CASCADE — GDPR-erased players' cooldown rows are removed.</summary>
    public Guid PlayerId { get; set; }

    /// <summary>UTC timestamp at which the decline / timeout occurred.</summary>
    public DateTimeOffset DeclinedAt { get; set; }

    /// <summary>
    /// Id of the proposal the player declined or timed out on. Stored as <c>text</c> at the SQL level —
    /// the proposal itself lives in Redis with a TTL and has no Postgres row to FK against.
    /// </summary>
    public Guid ProposalId { get; set; }
}
