// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 GameKit contributors

using System;

namespace GameKit.Matchmaking.Entities;

/// <summary>
/// Analytics-only async-write row representing a single matchmaking ticket (MATCH-02).
/// Redis remains the source of truth for the live queue (MATCH-04) — this row is
/// drained from an in-memory <c>Channel&lt;TicketEvent&gt;</c> by the analytics
/// drain service (CONTEXT.md D-15).
/// </summary>
/// <remarks>
/// <para>
/// <see cref="PartyId"/> is NULLABLE — solo enqueue (1-player ticket) does not require
/// a <see cref="Party"/> row. The matcher writes a placeholder party row only when
/// 2+ players queue together. The FK is restrict / set-null at the Postgres level
/// (NOT cascade) so cancelling a ticket leaves the party intact (CONTEXT.md D-04).
/// </para>
/// <para>
/// <see cref="SessionId"/> is NULLABLE — the ticket exists in non-terminal states
/// (Queued / Proposed) before the proposal succeeds and the <c>game_session</c> is
/// created. On <see cref="TicketStatus.Matched"/>, the matcher patches this column
/// with the new session id.
/// </para>
/// <para>
/// <see cref="Status"/> is stored as <c>integer</c> at the SQL level (Phase 5 mandatory
/// — Phase 4 was bitten by <c>HasConversion&lt;string&gt;()</c>). The index
/// <c>(LadderId, PoolName, Status)</c> supports the reconciler sweep that catches
/// abandoned tickets (Plan 05-06).
/// </para>
/// </remarks>
public sealed class MatchmakingTicket
{
    /// <summary>Ticket id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Optional FK → <see cref="Party.Id"/>. Null for solo enqueue. NOT cascade-delete —
    /// cancelling a ticket leaves the party row intact (CONTEXT.md D-04).
    /// </summary>
    public Guid? PartyId { get; set; }

    /// <summary>FK → <c>gamekit.ladders.Id</c> (Rankings package). Restrict-delete.</summary>
    public Guid LadderId { get; set; }

    /// <summary>
    /// Logical pool name within the ladder (default <c>"default"</c>). Multiple pools per
    /// ladder support region affinity or game-mode segmentation; v1 uses the default pool.
    /// </summary>
    public required string PoolName { get; set; }

    /// <summary>
    /// Ticket status. Stored as <c>integer</c> (Phase 5 mandatory) — no
    /// <c>HasConversion&lt;string&gt;()</c> applied.
    /// </summary>
    public TicketStatus Status { get; set; }

    /// <summary>
    /// Ticket type. Stored as <c>integer</c> (Phase 5 mandatory) — no
    /// <c>HasConversion&lt;string&gt;()</c> applied. Default <see cref="MatchmakingTicketType.Normal"/>.
    /// <see cref="MatchmakingTicketType.Backfill"/> tickets are inserted into the Redis queue
    /// with score <c>0</c> so they are processed before all Normal tickets.
    /// </summary>
    public MatchmakingTicketType TicketType { get; set; } = MatchmakingTicketType.Normal;

    /// <summary>UTC timestamp at which the ticket was enqueued. Drives bracket-flex curve (D-11).</summary>
    public DateTimeOffset QueuedAt { get; set; }

    /// <summary>UTC timestamp at which the ticket reached a terminal state. Null while non-terminal.</summary>
    public DateTimeOffset? TerminalAt { get; set; }

    /// <summary>FK → <c>gamekit.game_sessions.Id</c> when the proposal succeeded. Null otherwise. ON DELETE SET NULL.</summary>
    public Guid? SessionId { get; set; }
}
