// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 GameKit contributors

using System;

namespace GameKit.Matchmaking.Entities;

/// <summary>
/// A durable party row (CONTEXT.md D-01 — parties are first-class Postgres entities, not
/// runtime-only). Has an owner <see cref="OwnerPlayerId"/>, a case-insensitive party code,
/// a state machine (<see cref="PartyState"/>), creation timestamp, and an optional
/// auto-expiry deadline.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="PartyCode"/> is enforced case-insensitive at the SQL level via Postgres
/// <c>citext</c> column type (Pitfall §9). The C# type is <see cref="string"/>; the
/// migration declares the column as <c>citext</c>. The Auth migration already creates
/// the <c>citext</c> extension (Phase 2 <c>20260418000000_AuthInitial</c>) so this
/// migration does NOT re-run <c>CREATE EXTENSION</c>.
/// </para>
/// <para>
/// Mid-queue-disconnect semantics (CONTEXT.md D-04): cancelling a ticket leaves the
/// party row intact. The party is durable; the ticket is transient. The matchmaking
/// <c>matchmaking_tickets</c> table therefore has NO <c>ON DELETE CASCADE</c> from
/// <c>parties</c> — the FK is restrict-only (or set-null where ticket survival matters
/// for analytics).
/// </para>
/// </remarks>
public sealed class Party
{
    /// <summary>Party id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Short, case-insensitive party code (Among Us / Jackbox / Fall Guys UX precedent;
    /// CONTEXT.md D-02). Crockford base32 alphabet recommended (no I/L/O/0/1) — generator
    /// lands in Plan 05-04. The SQL column is <c>citext NOT NULL UNIQUE</c>; case-insensitive
    /// comparison is a SQL-level guarantee.
    /// </summary>
    public required string PartyCode { get; set; }

    /// <summary>
    /// Lifecycle state. Stored as <c>integer</c> (Phase 5 mandatory) — no
    /// <c>HasConversion&lt;string&gt;()</c> applied.
    /// </summary>
    public PartyState State { get; set; }

    /// <summary>
    /// FK → <c>gamekit.players.Id</c> (the canonical player, NOT a player identity).
    /// Cross-provider parties are permitted (CONTEXT.md D-05); Steam-linked and
    /// Discord-linked players share a <c>Player</c> row from Phase 2's multi-identity model.
    /// </summary>
    public Guid OwnerPlayerId { get; set; }

    /// <summary>UTC timestamp at which the party row was created.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Optional auto-expiry timestamp. Null when the party has no scheduled expiry.</summary>
    public DateTimeOffset? ExpiresAt { get; set; }
}
