// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 GameKit contributors

using System;

namespace GameKit.Matchmaking.Entities;

/// <summary>
/// Join-row binding a <see cref="Party"/> to a <c>Player</c>. References the canonical
/// <c>gamekit.players.Id</c> — Steam-linked and Discord-linked players can share a party
/// because both identities share a single <c>Player</c> row (CONTEXT.md D-05; Phase 2's
/// multi-identity model).
/// </summary>
/// <remarks>
/// <para>
/// The unique constraint on <c>(PartyId, PlayerId)</c> prevents duplicate-member rows for
/// the same party + player pair. Single-active-party-per-player is enforced in
/// application code via a SERIALIZABLE transaction (RESEARCH §Decision 12 + §OQ-2) rather
/// than a partial unique index, mirroring how Phase 2 handles the GuestUpgrade race.
/// </para>
/// <para>
/// <see cref="PlayerId"/> is restrict-delete (NOT set-null) because GDPR tombstoning is
/// handled at the <c>Player</c> level in Phase 1's design — the player row's hard-delete
/// path cascades through the matchmaking tables via <c>ON DELETE</c> rules established
/// in the Phase 5 migration (Plan 05-02 Task 3).
/// </para>
/// </remarks>
public sealed class PartyMember
{
    /// <summary>Row id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>FK → <see cref="Party.Id"/> (ON DELETE CASCADE — dropping a party drops its members).</summary>
    public Guid PartyId { get; set; }

    /// <summary>
    /// FK → <c>gamekit.players.Id</c> (the canonical player, NOT a <c>player_identity</c>).
    /// Cross-provider party membership is honored — CONTEXT.md D-05.
    /// </summary>
    public Guid PlayerId { get; set; }

    /// <summary>UTC timestamp at which the player joined the party.</summary>
    public DateTimeOffset JoinedAt { get; set; }
}
