// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 GameKit contributors

using System;

namespace GameKit.Matchmaking.Entities;

/// <summary>
/// Per-ticket lifecycle event row drained from an in-memory <c>Channel&lt;TicketEvent&gt;</c>
/// by the analytics drain service (CONTEXT.md D-15). Recorded events cover the eight
/// states pinned by CONTEXT.md D-18.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="EventType"/> is stored as <c>integer</c> (Phase 5 mandatory; Phase 4 was
/// bitten by <c>HasConversion&lt;string&gt;()</c>). Numeric values mirror
/// <see cref="TicketStatus"/> so the event taxonomy aligns with the corresponding
/// ticket-status transition.
/// </para>
/// <para>
/// <see cref="Payload"/> is an optional JSONB column carrying event-specific data — e.g.
/// <c>proposalId</c> for <see cref="TicketEventType.Proposed"/>, <c>sessionId</c> for
/// <see cref="TicketEventType.Matched"/>. Stored as a JSON string in C# but with
/// <c>jsonb</c> column type in Postgres (set in <c>TicketEventConfiguration</c>).
/// </para>
/// </remarks>
public sealed class TicketEvent
{
    /// <summary>Event row id — UUIDv7 generated by <c>IIdGenerator</c>.</summary>
    public Guid Id { get; set; }

    /// <summary>FK → <see cref="MatchmakingTicket.Id"/> (ON DELETE CASCADE — ticket-delete cascades to events).</summary>
    public Guid TicketId { get; set; }

    /// <summary>Event type. Stored as <c>integer</c> (Phase 5 mandatory).</summary>
    public TicketEventType EventType { get; set; }

    /// <summary>UTC timestamp at which the event was recorded.</summary>
    public DateTimeOffset OccurredAt { get; set; }

    /// <summary>
    /// Optional event-specific payload. JSON string at the C# level; <c>jsonb</c> at the
    /// SQL level. Null when no extra context is recorded.
    /// </summary>
    public string? Payload { get; set; }
}
